### ISSUE TITLE
Create a forumula for column B

### ISSUE THREAD

**Issue by ghost** [KeyboardPlaying/xls-time-tracker#19]
The B column is currently a user input, while it could be calculated from the C-F columns.
I think this wouldn't create circular dependencies.

![horaires](https://cloud.githubusercontent.com/assets/3389277/8931225/e5bdfeb2-3534-11e5-9be1-59e1dab27dbb.png)

**Comment by cyChop** [comment]
In version 2, column B has been split:
- B is now the _Profile_, which is calculated the same way as it was in version 1 but is customizable.
- C is the time ratio, which can be used to tell the tracker whether the day was full time, half time or something else.

I think it best to leave B untouched, since it allows to see if a line was forgotten (either you need to fill your time or set the profile to A).

Column C however could be pre-calculated to 0,5 or 1 based on the ins and outs. This would moreover ease the migration from version 1 to version 2.

### To do
- [x] Change C's default initialization:
  - If a profile is set
    - If time is typed
      - If total time < configurable ratio \* total day time for profile
        - &rightarrow; C = 0,5
      - Else
        - &rightarrow; C = 1
      - Fi
    - Else
      - &rightarrow; C = 1
    - Fi
  - Else
    - &rightarrow; C = empty
  - Fi
- [x] Add the ratio configuration to a technical section in the configuration tab (or to a new hidden technical tab)
