### ISSUE TITLE
Initial status is debit

### ISSUE THREAD

**Issue by ghost** [KeyboardPlaying/xls-time-tracker#27]
When initially opening the workbook, all past days are accounted as a debit because they are assign to the rule set 1.

![capture](https://cloud.githubusercontent.com/assets/3389277/11926268/a334608e-a7c3-11e5-9bf9-f82d9055a136.PNG)

To start a new account in the middle of the year, we must first remove the column B values in order to get the balance straight. Sadly since the year cell is merged we can't delete the column values by selecting the column itself.

A good first step could be to unmerge A1 ?

**Comment by cyChop** [comment]
Not sure if deleting all column is a good solution, though. The initial values are set through a formula which is 1 on week days, empty otherwise. Deleting the whole column means you will have to set manually all values in B until the end of the year (which might not be a problem when starting in December but much more a pain when starting in February).

I'd recommend one of two things:
- Dirty but easy:
  1. Set profile `1` to `00:00` a day.
  2. Create a profile `2` with your actual constraints.
  3. Use profile `2` for your working days, leave profile `1` for days before your working period.
- Cleaner and not much harder:
  1. Expand January and the current month.
  2. Select the cell in column B on the day previous to your start.
  3. While holding shift, click the cell in column B on January 1st.
  4. Press <kbd>Del</kbd>.
  5. Enjoy!

These workarounds will do for now. Another solution may be studied later if need be.
